"use client";

import { Heart } from "lucide-react";

import Button from "@/components/ui/Button";
import IconButton from "@/components/ui/IconButton";

import Card, {
  CardAction,
  CardContent,
  CardFooter,
  CardHeader,
} from "@/components/ui/Card";

export default function HomePage() {
  return (
    <main className="flex min-h-screen items-center justify-center p-10">
      <Card
        variant="interactive"
        hoverable
        className="w-[420px]"
      >
        <CardHeader>
          <h2 className="text-2xl font-bold">
            AI Playlist
          </h2>
        </CardHeader>

        <CardContent>
          <p>
            Relaxing lo-fi beats generated by musX AI.
          </p>
        </CardContent>

        <CardFooter>
          <span>25 Songs</span>

          <CardAction>
            <Button size="sm">
              Play
            </Button>

            <IconButton
              icon={<Heart size={18} />}
              tooltip="Like"
            />
          </CardAction>
        </CardFooter>
      </Card>
    </main>
  );
}